Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  # VM 1
  config.vm.define "jmafueniS" do |jmafueniS|
    jmafueniS.vm.hostname = "jmafueniS"
    jmafueniS.vm.network "private_network", ip: "192.168.56.110"

    jmafueniS.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
        jmafueniS.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://get.k3s.io -o /tmp/install-k3s.sh
        sh /tmp/install-k3s.sh server --node-ip 192.168.56.110 
        # Attendre que le token soit généré, puis le partager
        while [ ! -f /var/lib/rancher/k3s/server/node-token ]; do sleep 1; done
        cp /var/lib/rancher/k3s/server/node-token /vagrant/token
      SHELL
  end

  # VM 2
  config.vm.define "jmafueniSW" do |jmafueniSW|
    jmafueniSW.vm.hostname = "jmafueniSW"
    jmafueniSW.vm.network "private_network", ip: "192.168.56.111"

    jmafueniSW.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    jmafueniSW.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io -o /tmp/install-k3s.sh
      K3S_URL=https://192.168.56.110:6443 \
      K3S_TOKEN=$(cat /vagrant/token) \
      sh /tmp/install-k3s.sh agent \
        --node-ip 192.168.56.111 \
        --flannel-iface eth1
    SHELL
  end
end